package com.company.pnsk;



public class EldEvent implements BaseEld{
    private String eventId;                         // "Event id"
    private long logId;                       // "Log id"
    private String eventSequenceId;                 // "Event sequence id"
    private String vehicleId;                       // "Vehicle Id"
    private long driverId;                    // "Driver id"
    private long coDriverId;                  // "Co-driver id"
    private String hardwareId;                      // "This is an internal id for the hardware"
    private long dateTime;                    // "Event trigger time"
    private String timeZoneOffset;                  // "Time zone"
    private String driverLocationDesc;              // "Driver location description"
    private String eventCode;                       // "Event code"
    private String eventType;                       // "Event type"
    private String dataChecksum;                    // "Checksum for event data"
    private String recordOrigin;                    // "Record origin"
    private String recordStatus;                    // "Record Status"
    private String closestCityName;                 // "Closest city name"
    private double closestCityDistance;             // "Distance to closest city"
    private String closestCityBearing;              // "Direction Coding"
    private double latitude;                        // "Latitude"
    private double longitude;                       // "Longitude"
    private String dataDiagnosticIndicator;         // "data diagnostic indicator"
    private String malfunctionIndicatorStatus;      // "Malfunction Indicator Status"
    private String commentAnnotation;               // "Driver comment annotation"
    private double elapsedEngineHours;              // "Elapsed engine hours"
    private double totalEngineHours;                // "Total engine hours"
    private int accumulatedVehicleMiles;            // "Accumulated vehicle miles"
    private int totalVehicleMiles;                  // ""
    private String distanceSinceLastLatLong;        // "The distance that driver drove since last position"
    private long createdDateTime;             // "DateTime of the creation"
    private long updatedDateTime;             // "DateTime of the modification"
    private String malfunctionCode;                 // "Malfunction code"
    private long certificationDate;           // "Data when event was ceritfied"
    private String signature;                       // "Binary representation of signature"
    private long originatorId;                // "The record originator id"
    private String originEventId;                   // "Event id"
}
